### ISSUE TITLE
ja era os bots bbb?

### ISSUE THREAD

**Issue by viperoz** [diofeher/bbbot#12]
DanielHe4rt disse no insta dele que a globo usou o código pra melhorar a segurança da votação, ele falou que quem manja de programação, consegue burlar facilmente, ele n vai mais atualizar..

e esse aqui não ta funcionando,depois do primeiro voto ele fica "processando seu voto" eternamente

**Comment by diofeher** [comment]
Isso é proteção do backend da Globo. Segue esse bot aqui que vai estar funcionando no paredão de hoje https://github.com/diofeher/bbb-v2
