### ISSUE TITLE
erro a selecionar imagem

### ISSUE THREAD

**Issue by ibonzanino** [diofeher/bbbot#5]
> bbbot@1.0.0 start /home/igor/www/bbbot
> cd src && node vote.js

Logged in.
Download captcha from URL: lâmpada
Get captcha: lâmpada | Position: lâmpada lâmpada_33.png True
lâmpada lâmpada_31.png True
lâmpada lâmpada_3.png True
lâmpada lâmpada_0.png True
lâmpada lâmpada_33.png True
lâmpada lâmpada_31.png True
lâmpada lâmpada_3.png True
lâmpada lâmpada_0.png True
lâmpada lâmpada_33.png True
lâmpada lâmpada_31.png True
lâmpada lâmpada_3.png True
lâmpada lâmpada_0.png True
lâmpada lâmpada_33.png True
lâmpada lâmpada_31.png True
lâmpada lâmpada_3.png True
lâmpada lâmpada_0.png True
lâmpada lâmpada_33.png True
lâmpada lâmpada_31.png True
lâmpada lâmpada_3.png True
lâmpada lâmpada_0.png True
0
(node:17550) UnhandledPromiseRejectionWarning: Error: Protocol error (Input.dispatchMouseEvent): Invalid parameters x: double value expected
    at /home/igor/www/bbbot/node_modules/puppeteer/lib/Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (/home/igor/www/bbbot/node_modules/puppeteer/lib/Connection.js:182:12)
    at Mouse.move (/home/igor/www/bbbot/node_modules/puppeteer/lib/Input.js:209:26)
    at Mouse.<anonymous> (/home/igor/www/bbbot/node_modules/puppeteer/lib/helper.js:112:23)
    at Mouse.click (/home/igor/www/bbbot/node_modules/puppeteer/lib/Input.js:235:14)
    at Mouse.<anonymous> (/home/igor/www/bbbot/node_modules/puppeteer/lib/helper.js:112:23)
    at clickOnElement (/home/igor/www/bbbot/src/utils.js:29:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async voteParticipant (/home/igor/www/bbbot/src/vote.js:68:3)
(node:17550) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17550) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by vinemarques** [comment]
Fiz um fix aqui...

https://github.com/diofeher/bbbot/pull/6

**Comment by mawippel** [comment]
Na verdade isso é problema de asíncronismo, se voce perceber, tá sendo printado `Get captcha:` antes de printar o resultado que vem do `compare_images.py`

**Comment by diofeher** [comment]
No caso tá dando um problema pq tá ele espera só o valor int do script em python. Acho que esqueci de remover o resto ai deu esse erro. Valeu pelo PR galera!
