### ISSUE TITLE
no module named cv2 

### ISSUE THREAD

**Issue by ibonzanino** [diofeher/bbbot#7]
Logged in.
Download captcha from URL: pincel
Traceback (most recent call last):
  File "compare_images.py", line 1, in <module>
    import cv2
ImportError: No module named cv2
(node:28324) UnhandledPromiseRejectionWarning: Error: Command failed: python compare_images.py "pincel"
Traceback (most recent call last):
  File "compare_images.py", line 1, in <module>
    import cv2
ImportError: No module named cv2

    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at voteParticipant (/home/igor/www/bbbot/src/vote.js:59:40)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:28324) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:28324) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by marciofmjr** [comment]
estou com o mesmo erro.. estou usando Mac OS

**Comment by mawippel** [comment]
Instalaram as dependências?

`pip install -r requirements.txt`

**Comment by ibonzanino** [comment]
> Instalaram as dependências?
> 
> `pip install -r requirements.txt`

após executar esse comando no console me retornou um erro diferente ao executar o bot

`Download captcha from URL: camisa
Traceback (most recent call last):
  File "compare_images.py", line 51, in <module>
    if remove_accents(target) not in remove_accents(name):
  File "/home/igor/www/bbbot/src/utils.py", line 40, in remove_accents
    return ''.join(x for x in unicodedata.normalize('NFKD', data) if x in string.ascii_letters).lower()
TypeError: normalize() argument 2 must be unicode, not str
(node:30683) UnhandledPromiseRejectionWarning: Error: Command failed: python compare_images.py "camisa"
Traceback (most recent call last):
  File "compare_images.py", line 51, in <module>
    if remove_accents(target) not in remove_accents(name):
  File "/home/igor/www/bbbot/src/utils.py", line 40, in remove_accents
    return ''.join(x for x in unicodedata.normalize('NFKD', data) if x in string.ascii_letters).lower()
TypeError: normalize() argument 2 must be unicode, not str

    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at voteParticipant (/home/igor/www/bbbot/src/vote.js:59:40)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:30683) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:30683) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by mawippel** [comment]
Você instalou o Python 3.7?

Se sim, o que aparece no console quando você verifica a versão do pip? (`pip --version`)

**Comment by lizarti** [comment]
Eu tive esse problema também. 

Não conheço Python, mas pelo que eu consegui entender, as dependências estavam sendo instaladas no diretório de instalação do Python (uso Windows, e aqui está em ` C:\Python37\Lib\site-packages`) mas este diretório não estava no `sys.path`. Então o Python não conseguia resolver as dependências.

Eu então adicionei esse diretório numa variável de ambiente chamada `PYTHONPATH`.

**Comment by diofeher** [comment]
Isso, vocês estão certos em como consertar. Atualizei o bot e as documentações, espero que esteja mais fácil de utilizar. Obrigado!
