### ISSUE TITLE
TypeError: Cannot read property 'click' of undefined

### ISSUE THREAD

**Issue by viperoz** [diofeher/bbbot#8]
boa tarde, bot faz tudo, entra no site, rola a pagina ate os participantes, mas não clica na opção que escolhi.

(node:12852) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'click' of undefined
    at voteParticipant (C:\Users\wallkp\Desktop\bbbot-master\src\vote.js:56:49)
(node:12852) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12852) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by lizarti** [comment]
A classe da lista dos participantes não é mais a mesma `_18p_tzl-nqcb9ABOQXokP0`. E sim `_33xB9lnxWiz4_roxOWYK_h`. Isso foi trocado há pouco tempo, creio que lá pelas 18h.

Basta alterar isso em `xpaths.participants` em `config.js`.

**Comment by mawippel** [comment]
Eles alteraram as imagens do Captcha também, pelo que vi.

**Comment by viperoz** [comment]
> A classe da lista dos participantes não é mais a mesma `_18p_tzl-nqcb9ABOQXokP0`. E sim `_33xB9lnxWiz4_roxOWYK_h`. Isso foi trocado há pouco tempo, creio que lá pelas 18h.
> 
> Basta alterar isso em `xpaths.participants` em `config.js`.

alterei, parou de dar erro, agora ele clica no participante, mas não seleciona a imagem do captcha pra finalizar o voto.
o Log fica sem erros, mas também não completa a ação rsrs

Logged in.
Download captcha from URL: Formiga

**Comment by lizarti** [comment]
É que não acha o captcha (pois foram majoritariamente alterados, como apontou o @mawippel). 
Fica travado sem nada pois o código cai na linha 61 do `vote.js`.

**Comment by kamikazerox** [comment]
> A classe da lista dos participantes não é mais a mesma `_18p_tzl-nqcb9ABOQXokP0`. E sim `_33xB9lnxWiz4_roxOWYK_h`. Isso foi trocado há pouco tempo, creio que lá pelas 18h.
> 
> Basta alterar isso em `xpaths.participants` em `config.js`.

Onde encontrou esse parâmetro de classe da lista?

**Comment by lizarti** [comment]
Não sei se entendi direito. É a classe da lista de `div`'s dos participantes lá da tela de votação.
Neste momento (olhei agora) a classe é `_1Y7EGDbQkmzYnNZcD4tztg`.

**Comment by sergiooak** [comment]
A globo toma duas medidas de prevenção de bots, a primeira mais básica é simples alterar as classes das `div`s, e a aoutra é adicionar novas imagens e novas variações de imagens...

O erro `TypeError: Cannot read property 'click' of undefined` acontecem quando as classes mudam.
Não tem muito o que fazer, é ficar nessa guerra de cão e gato

**Comment by sergiooak** [comment]
Sugestão para o problema das classes alterando, ao invés de procurar as divs dos participantes com o xPath, utilizar um seletor css pela estrutura do HTML, que é imutável.

vote.js linha 53
```diff
- const participantes = await page.$$(xpaths.participants);
+ const participantes = await page.$$('#roulette-root > div > div div:nth-child(4) > div');
```
Aí pode até remover a linha 21 do config.js
```diff
- participants: '[class="_1Y7EGDbQkmzYnNZcD4tztg"]',
```

Não irei abrir uma pull request agora, por pura preguiça, se puderem implementar, irá solucionar o problemas das classes se alterando.

**Comment by diofeher** [comment]
Fala galera, atualizei nas versões mais novas, obrigado por comentar!
